### ISSUE TITLE
Update menu for Zabbix 4.4

### ISSUE THREAD

**Issue by rlfink** [stdonato/zabdash#10]
Please update the menu section for Zabbix 4.4, 'Users' label.  Should be:
                                [
                                        'url' => 'zabbix.php',
                                        'action' => 'user.list',
                                        'active_if' => ['user.edit', 'user.list'],
                                        'label' => _('Users')
                                ],

**Comment by stdonato** [comment]
Thanks. I'll check.

**Comment by stdonato** [comment]
Menu updated.
