### ISSUE TITLE
A multiple problem sign (RED) becomes GREEN when you get close enough

### ISSUE THREAD

**Issue by mbuyukkarakas** [stdonato/zabdash#11]
Hello,

As you can se in first image, the red point tells us there are at least 2 errors on hosts. And obviously it's red.

<img width="632" alt="resim" src="https://user-images.githubusercontent.com/15248990/74213233-6374bb80-4ca9-11ea-8f90-b674e82ddd85.png">

but when you get close enough, it splits to two green host signs.

<img width="632" alt="resim" src="https://user-images.githubusercontent.com/15248990/74213256-6ff91400-4ca9-11ea-86b9-b971f7a50fda.png">

It seems there is a cache for this map or something else which is not refreshing. Am I correct ? Or what can be the reason for this ?

Thank you.

**Comment by stdonato** [comment]
Hi, cluster marker will be red if any host have a trigger incident.
Hosts markers will show triggers colors according hosts triggers. 
I'm trying set different color for cluster.

**Comment by mbuyukkarakas** [comment]
but none of these hosts have a trigger. (picture 2). when you zoom it everything is fine.
