### ISSUE TITLE
Grouped hosts are always displayed with red icon.

### ISSUE THREAD

**Issue by mbuyukkarakas** [stdonato/zabdash#12]
If multiple hosts are at same location, when they are grouped, the icon always turns red. you can see my example below with two hosts represented by red icon.

<img width="812" alt="Screen Shot 2020-06-05 at 17 43 08" src="https://user-images.githubusercontent.com/15248990/83890247-349cbc80-a754-11ea-82c1-50fb1d8be192.png">

but when I zoom it, the hosts are splitting and they are becoming green.

<img width="812" alt="Screen Shot 2020-06-05 at 17 43 22" src="https://user-images.githubusercontent.com/15248990/83890288-3e262480-a754-11ea-85d1-c5bcc3ea1514.png">

my hosts dont have any trigger open, so everything fine but zabdash shows them with an red icon when the are grouped.

**Comment by mbuyukkarakas** [comment]
Hello, did you had the chance to take a look at this ?
thanks

**Comment by stdonato** [comment]
I'm suspending the development of my add-ons due the change new Zabbix 5.x to MVC. The new structure demands a large rewrite of code, which i can't do at moment.
