### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by hostbyte** [stdonato/zabdash#3]
[root@mon01 zabdash]# tail -f /var/log/httpd/error_log
[Wed Nov 21 14:56:18.006178 2018] [:error] [pid 19234] [client 91.121.174.48:55065] script '/usr/share/zabbix/xiaoma.php' not found or unable to stat
[Wed Nov 21 14:56:18.248877 2018] [:error] [pid 19234] [client 91.121.174.48:55065] script '/usr/share/zabbix/xiaomae.php' not found or unable to stat
[Wed Nov 21 14:56:18.491658 2018] [:error] [pid 19234] [client 91.121.174.48:55065] script '/usr/share/zabbix/xiaomar.php' not found or unable to stat
[Wed Nov 21 14:56:18.734768 2018] [:error] [pid 19234] [client 91.121.174.48:55065] script '/usr/share/zabbix/qq.php' not found or unable to stat
[Wed Nov 21 14:56:18.977553 2018] [:error] [pid 19234] [client 91.121.174.48:55065] script '/usr/share/zabbix/data.php' not found or unable to stat
[Wed Nov 21 14:56:19.220786 2018] [:error] [pid 19234] [client 91.121.174.48:55065] script '/usr/share/zabbix/log.php' not found or unable to stat
[Wed Nov 21 14:56:19.463967 2018] [:error] [pid 19234] [client 91.121.174.48:55065] script '/usr/share/zabbix/fack.php' not found or unable to stat
[Wed Nov 21 14:56:19.706824 2018] [:error] [pid 19234] [client 91.121.174.48:55065] script '/usr/share/zabbix/angge.php' not found or unable to stat
[Wed Nov 21 15:34:35.288612 2018] [:error] [pid 19241] [client 177.74.142.10:42750] PHP Fatal error:  Call to undefined function ZabbixApi\\posix_getuid() in /usr/share/zabbix/zabdash/lib/ZabbixApiAbstract.class.php on line 498, referer: http://168.205.176.29/zabdash/
[Wed Nov 21 15:41:18.390952 2018] [:error] [pid 19236] [client 177.74.142.10:43000] PHP Fatal error:  Call to undefined function ZabbixApi\\posix_getuid() in /usr/share/zabbix/zabdash/lib/ZabbixApiAbstract.class.php on line 498, referer: http://168.205.176.29/zabdash/

**Comment by hostbyte** [comment]
Hello! I'm using CentOS 7 with Zabbix 4.0
After installing php-process, I no longer have the error. But when I try to login, it goes back to the login screen

**Comment by stdonato** [comment]
Do you make the changes in config.php file?
