### ISSUE TITLE
The host is displayed on map but no trigger / warning sign

### ISSUE THREAD

**Issue by mbuyukkarakas** [stdonato/zabdash#6]
Thanks for this great plugin.
I installed it on my zabbix 4.4 test server. And setted the coordinates for default zabbix server. The zabbix server has already an trigger but only I can see the host sign. Nothing about trigger.
How can I display the severity of the trigger by color or number of open trigggers ?

Thank you.

<img width="1577" alt="resim" src="https://user-images.githubusercontent.com/15248990/72823387-acc28400-3c84-11ea-9bf2-389c46fb17d2.png">

**Comment by stdonato** [comment]
Hi,
This is the first version using openstreetmaps and i still learning about it.
The marker color would reflect the trigger color and green for no trigger.
Maybe i put a legend in page top. 
Show the number of trigger is on my to do list.

**Comment by mbuyukkarakas** [comment]
Yes you're right. The object color depends on triggers severity. When I changed to Information, it became blue also.
So please take it as a feature request ;
- to add number of triggers
- to be able to change icon type

Thank you.

**Comment by stdonato** [comment]
New map with trigger count.
![zabdas-map-1](https://user-images.githubusercontent.com/7674445/72847060-2acc5e00-3c78-11ea-9b45-3e3dba02a832.png)

**Comment by stdonato** [comment]
Can you try the new map page? Get the new file and copy to your zabdash/map folder:
https://github.com/stdonato/zabdash/blob/master/map/map.php

**Comment by mbuyukkarakas** [comment]
It worked :)

![image](https://user-images.githubusercontent.com/15248990/72877335-c8bc3900-3d09-11ea-8b14-5aa7650d554c.png)
