### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'locales' (T_STRING) in /usr/share/zabbix/map/config.php on line 16

### ISSUE THREAD

**Issue by mbuyukkarakas** [stdonato/zabdash#9]
Some of our installations has received this error.

PHP Parse error:  syntax error, unexpected 'locales' (T_STRING) in /usr/share/zabbix/map/config.php on line 16

First look, there is no difference than other running servers.

`[root@zabbix zabbix]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

config.php

<?php

require_once 'inc/functions.inc.php';

$zabServer = "1.1.11";
$zabUser = "zabdash";
$zabPass = "cccccccccc";
$zabURL = "http://1.1.1.1/";

$useridlang = get_userid(CWebUser::getSessionCookie());
$lang = get_user_lang($useridlang);

$version = '1.1.9"

//Translate option: en_US or pt_BR
$labels = include_once 'locales/'.$lang.'.php';

?>

thank you.

**Comment by mbuyukkarakas** [comment]
Update ;

We used to use default config.php. After renaming config.php and making a copy of config.php-example it worked.

But it can be good to know why the default config.php triggers this error.
thank you.

**Comment by stdonato** [comment]
Fixed.
